spring:
  application:
    name: RegAuthSystem
  profiles:
    active: beta #默認為開發環境
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    
