regAuthSystem:
  version: 0.1.0


spring:
  application:
    name: RegAuthSystem
  profiles:
    active: beta
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    

Configuration:
  status: debug
  Appenders:
    Console:
      name: STDOUT
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: STDOUT
